### ISSUE TITLE
サンプルアプリケーションの作成

### ISSUE THREAD

**Issue by boke0** [mitama-org/mitama#24]
Mitamaの機能を極力用いたサンプルアプリを開発してください。

特に、Mitamaのsqliteラッパは絶対に用いること。

examplesディレクトリだけを設置したfeature/sampleブランチを用意するので、例外的にそこからブランチを切ってください。また、一旦プルリクエストはfeature/sampleへのマージを要求してください。

**Comment by takuan517** [comment]
wireframe
![mitama](https://user-images.githubusercontent.com/50577904/91211139-3d949d00-e749-11ea-990a-4cdff649c016.png)

**Comment by boke0** [comment]
feature/samplesつくったよ

**Comment by takuan517** [comment]
sampleって起動したときに立ち上がるってことだよね

**Comment by takuan517** [comment]
defalut appのような気もした

**Comment by boke0** [comment]
いや、アプリの作成例程度の認識で良い

**Comment by boke0** [comment]
こんなことできるんやなーっていうのを作ってもらって、適当にホスティングして試せるようなやつを
samples/にためときたい

**Comment by takuan517** [comment]
そのファイルを元に変更していくわけじゃないの？？他のフレームワークみたいに

**Comment by boke0** [comment]
それはそれだな

**Comment by boke0** [comment]
ちょいそれ別イシュー立てる

**Comment by takuan517** [comment]
それがここで書いてるワイヤーフレームの想定だった

**Comment by takuan517** [comment]
作り方とかはドキュメントに書けばいいと思う

**Comment by boke0** [comment]
そうなんだけど、Sphinxで書いたドキュメントだけでアプリ作れる人いると思えないし、チュートがてら一個ぐらいはサンプルがあったほうが良いんでは？

**Comment by takuan517** [comment]
sample-appってプロジェクトを俺らで作ってそれをドキュメントに乗せれば、、いいんじゃ、、？

**Comment by boke0** [comment]
それだったら結局作るんでここでやっちゃって良さそう

**Comment by takuan517** [comment]
ここで作ったらuserの作成したプロジェクトにも入るんだよね、、？

**Comment by boke0** [comment]
いや、/samplesディレクトリに置かれるだけだから、インストールしたらゴミになる
